### ISSUE TITLE
Restore rootFS and re-enabling OTA updates is broken

### ISSUE THREAD

**Issue by kasti0** [TheOdysseyJB/Odyssey#18]
- I can’t switch off the „block OTA updates“ switch in the settings, therefore after restoring rootFS my updates where still blocked
- after restoring rootFS for example my banking app still couldn’t open because it detected the jailbreak or some leftover files

Because of these bugs I had to completely restore and set up my iPhone as new. On the unc0ver jailbreak this never was an issue.

**Comment by demhademha** [comment]
Uicache also doesn't occur, making the icons from the jailbreak stay, IE sileo, filza.

**Comment by Diatrus** [comment]
Block updates is an issue you have leftover from unc0ver or something else you've done. Block updates isn't even available on Odyssey. The other part is some tweak you installed left files in /var, which we can't solve.
