### ISSUE TITLE
11 errors in compiling

### ISSUE THREAD

**Issue by Light-YT** [TheOdysseyJB/Odyssey#2]
Error Group
/Users/Light/Desktop/Odyssey/Odyssey/app/Reachability.swift:40:8: Identifier Name Violation: Variable name should start with a lowercase character: 'ReachabilityChangedNotification' (identifier_name)
/Users/Light/Desktop/Odyssey/Odyssey/app/Reachability.swift:353:9: Identifier Name Violation: Variable name should be between 2 and 40 characters long: 'W' (identifier_name)
/Users/Light/Desktop/Odyssey/Odyssey/app/Reachability.swift:354:9: Identifier Name Violation: Variable name should be between 2 and 40 characters long: 'R' (identifier_name)
/Users/Light/Desktop/Odyssey/Odyssey/app/Reachability.swift:356:9: Identifier Name Violation: Variable name should be between 2 and 40 characters long: 't' (identifier_name)
/Users/Light/Desktop/Odyssey/Odyssey/app/Reachability.swift:358:9: Identifier Name Violation: Variable name should be between 2 and 40 characters long: 'C' (identifier_name)
/Users/Light/Desktop/Odyssey/Odyssey/app/Reachability.swift:359:9: Identifier Name Violation: Variable name should be between 2 and 40 characters long: 'D' (identifier_name)
/Users/Light/Desktop/Odyssey/Odyssey/app/Reachability.swift:360:9: Identifier Name Violation: Variable name should be between 2 and 40 characters long: 'l' (identifier_name)
/Users/Light/Desktop/Odyssey/Odyssey/app/AppVersionManager.swift:41:92: Force Cast Violation: Force casts should be avoided. (force_cast)
/Users/Light/Desktop/Odyssey/Odyssey/app/AppVersionManager.swift:37:34: Force Try Violation: Force tries should be avoided. (force_try)
/Users/Light/Desktop/Odyssey/Odyssey/app/electra-dummy.swift:82:1: Identifier Name Violation: Function name should start with a lowercase character: 'ObjcTryCatch(_:)' (identifier_name)
Uncategorized Group
Command PhaseScriptExecution emitted errors but did not return a nonzero exit code to indicate failure

**Comment by Light-YT** [comment]
Can compile despite these errors but closes when you start the application

**Comment by youngzzzzzzz** [comment]
same here and crash while run the app

**Comment by Diatrus** [comment]
These are just SwiftLint errors. @youngzzzzzzz your error was just solved in the latest commit.
