### ISSUE TITLE
Library not loaded when trying to running

### ISSUE THREAD

**Issue by fatgrass** [TheOdysseyJB/Odyssey#3]
Error Log:

Incident Identifier: 2EC1A18C-FB78-474B-A315-E4F64CB3B70F
CrashReporter Key:   22a84a35ddf132a7bbf47e96ad1c3e8855ff4926
Hardware Model:      iPhone11,8
Process:             Odyssey [1256]
Path:                /private/var/containers/Bundle/Application/2E9AFCD1-AEB2-46A7-A6FE-008218B96EED/Odyssey.app/Odyssey
Identifier:          org.coolstartmp.odyssey
Version:             1 (1.0.1)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           org.coolstartmp.odyssey [1107]

Date/Time:           2020-08-29 16:44:49.2269 +0800
Launch Time:         2020-08-29 16:44:49.1801 +0800
OS Version:          iPhone OS 13.4.1 (17E262)
Release Type:        User
Baseband Version:    2.05.13
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, Library not loaded: @rpath/SwiftZSTD.framework/SwiftZSTD | Referenced from: /private/var/containers/Bundle/Application/2E9AFCD1-AEB2-46A7-A6FE-008218B96EED/Odyssey.app/Odyssey | Reason: image not found
Triggered by Thread:  0

Thread 0 Crashed:
0   dyld                          	0x00000001006d8f30 __abort_with_payload + 8
1   dyld                          	0x00000001006e066c abort_with_payload_wrapper_internal + 104
2   dyld                          	0x00000001006e06a0 unw_set_reg.cold.1 + 0
3   dyld                          	0x00000001006dd354 invocation function for block in dyld::removeImage+ 349012 (ImageLoader*) + 0
4   dyld                          	0x000000010068f50c dyld::_main+ 29964 (macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) + 5388
5   dyld                          	0x000000010068922c dyldbootstrap::start+ 4652 (dyld3::MachOLoaded const*, int, char const**, dyld3::MachOLoaded const*, unsigned long*) + 432
6   dyld                          	0x0000000100689038 _dyld_start + 56

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000016fbf6bd0   x3: 0x000000000000009d
    x4: 0x000000016fbf67d0   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x2f7070612e796573  x11: 0x0a7965737379644f
   x12: 0x20200a7965737379  x13: 0x203a6e6f73616552  x14: 0x6f6e206567616d69  x15: 0x00646e756f662074
   x16: 0x0000000000000209  x17: 0x00000001006d3510  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016fbf67d0  x21: 0x000000000000009d  x22: 0x000000016fbf6bd0  x23: 0x0000000000000001
   x24: 0x0000000000000006  x25: 0x00000001006f8000  x26: 0x00000001006f8000  x27: 0x00000001006f8000
   x28: 0x0000000000000001   fp: 0x000000016fbf67a0   lr: 0x00000001006e066c
    sp: 0x000000016fbf6760   pc: 0x00000001006d8f30 cpsr: 0x00000000
   esr: 0x56000080  Address size fault

Binary Images:
0x100208000 - 0x100267fff Odyssey arm64e  <2f195a146bed3a76a8856fff07d07bea> /var/containers/Bundle/Application/2E9AFCD1-AEB2-46A7-A6FE-008218B96EED/Odyssey.app/Odyssey
0x100688000 - 0x1006effff dyld arm64e  <592a4b82e7623dc69409d35dd4a89b6f> /usr/lib/dyld
0x19ebbb000 - 0x19ebecfff libobjc.A.dylib arm64e  <fbeed962693f3ee780ce9764def56b78> /usr/lib/libobjc.A.dylib
0x19ecda000 - 0x19ed37fff libc++.1.dylib arm64e  <cd3dd206dfc53d7a87fa84c638fe62a4> /usr/lib/libc++.1.dylib
0x19ed7a000 - 0x19f0f7fff CoreFoundation arm64e  <9624aafd54373772a5070f357875808d> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
0x19f0f8000 - 0x19f162fff SystemConfiguration arm64e  <51f61d30a54a32fe83e0c07fde17d338> /System/Library/Frameworks/SystemConfiguration.framework/SystemConfiguration
0x19f163000 - 0x19f42efff Foundation arm64e  <2b7bd2f310a83cba9de35e1f48d9213e> /System/Library/Frameworks/Foundation.framework/Foundation
0x19fe1c000 - 0x19fec2fff IOKit arm64e  <0673030ac3a53e6684e39a9983b8611b> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
0x1a59bd000 - 0x1a5c18fff QuartzCore arm64e  <37156f210d1538c39745b1f78f698da8> /System/Library/Frameworks/QuartzCore.framework/QuartzCore
0x1a5ce3000 - 0x1a6258fff CoreGraphics arm64e  <f99bd63973643a6c91c44bf97236fea4> /System/Library/Frameworks/CoreGraphics.framework/CoreGraphics
0x1ac6ac000 - 0x1aca78fff libswiftCore.dylib arm64e  <4fccc10af94b3d9aa701f22c7199b6db> /usr/lib/swift/libswiftCore.dylib
0x1c9e25000 - 0x1c9e25fff UIKit arm64e  <d03b0c06cb26377ca15f476e59f174b8> /System/Library/Frameworks/UIKit.framework/UIKit
0x1d4a51000 - 0x1d4a52fff libSystem.B.dylib arm64e  <faef0957c9713753b07f5798e30639e0> /usr/lib/libSystem.B.dylib
0x1d56bf000 - 0x1d56cdfff libswiftCoreGraphics.dylib arm64e  <61b51730d9443fa5914828623ab7bdf8> /usr/lib/swift/libswiftCoreGraphics.dylib
0x1d571f000 - 0x1d5728fff libswiftDarwin.dylib arm64e  <e213dc226c583936a1db6762227df23c> /usr/lib/swift/libswiftDarwin.dylib
0x1d5729000 - 0x1d5743fff libswiftDispatch.dylib arm64e  <b6b97ef6478f3da0a93033468d974dff> /usr/lib/swift/libswiftDispatch.dylib
0x1d5744000 - 0x1d58bdfff libswiftFoundation.dylib arm64e  <af6284e22e0f3860a1f1f7155ce1e4da> /usr/lib/swift/libswiftFoundation.dylib
0x1d596f000 - 0x1d5975fff libswiftObjectiveC.dylib arm64e  <fe436c21f7df3816ab818f23a38903f4> /usr/lib/swift/libswiftObjectiveC.dylib

EOF

**Comment by Diatrus** [comment]
Are you on the latest Odyssey version, and does this consistently happen?

**Comment by youngzzzzzzz** [comment]
same here
