### ISSUE TITLE
Breaking tweak developers tweak!!

### ISSUE THREAD

**Issue by ca13ra1** [TheOdysseyJB/Odyssey#30]
So I had the pleasure of installing Odyssey to only find out you don't allow **Plutil** by _sbingner_ which my tweak **WeatherWidget** needs as a dependency. So not allowing technically breaks my tweak in return.

Plutil is **essential** or the tweak won't work plain and simple. Coolstar can you please give some guidance as I cannot even install plutil manually without `conflicting packages - not installing com.bingner.plutil`

**Comment by chrismonster13** [comment]
plutil is on the Procursus repo. You can't have 2 repos with 2 bootstraps added cuz it will cause issues. Install the one from the Procursus repo. I've been using your tweak just fine with it.

**Comment by ca13ra1** [comment]
@chrismonster13 I can’t seem t find it on that repo? Is it under a different name?

**Comment by chrismonster13** [comment]
Ohhhh I got ya I didn't know it depended on essential. Sorry I missed that lol

**Comment by ca13ra1** [comment]
@chrismonster13 Also needs to install prior to installing WeatherWidget and a full reboot. Semi-tether was a bit different but it’s working. Appreciate your help. Updated my depiction with proper instructions!
