### ISSUE TITLE
Error jailbreaking. iPhone 6s Plus, iOS 13.7.

### ISSUE THREAD

**Issue by Lifr0m** [TheOdysseyJB/Odyssey#31]
![image](https://user-images.githubusercontent.com/67340721/99885852-e66b6f00-2c48-11eb-80d6-46ba879c990d.png)

**Comment by Lifr0m** [comment]
Settings:
![image](https://user-images.githubusercontent.com/67340721/99885884-24689300-2c49-11eb-82ff-cacbe0419a50.png)![image](https://user-images.githubusercontent.com/67340721/99885889-2894b080-2c49-11eb-84f7-40d87e4e289e.png)![image](https://user-images.githubusercontent.com/67340721/99885891-2af70a80-2c49-11eb-8992-bc76cb5dd6e8.png)

**Comment by SsNipeR1** [comment]
Чел, как я вижу ты русский, (по оператору узнал), так вот, уже есть issue #29 и в нем я спрашивал ТО ЖЕ САМОЕ. Зачем открывать новые проблемы и засорять репозиторий, если можно спросить тоже самое у меня в #29 ?

**Comment by Lifr0m** [comment]
> Чел, как я вижу ты русский, (по оператору узнал), так вот, уже есть issue #29 и в нем я спрашивал ТО ЖЕ САМОЕ. Зачем открывать новые проблемы и засорять репозиторий, если можно спросить тоже самое у меня в #29 ?

Ты не назвал ни модель телефона, ни кинул скрины настроек, ни лог ошибки в целом...

**Comment by Lifr0m** [comment]
> Чел, как я вижу ты русский, (по оператору узнал), так вот, уже есть issue #29 и в нем я спрашивал ТО ЖЕ САМОЕ. Зачем открывать новые проблемы и засорять репозиторий, если можно спросить тоже самое у меня в #29 ?

Не заметил

**Comment by Lifr0m** [comment]
> Чел, как я вижу ты русский, (по оператору узнал), так вот, уже есть issue #29 и в нем я спрашивал ТО ЖЕ САМОЕ. Зачем открывать новые проблемы и засорять репозиторий, если можно спросить тоже самое у меня в #29 ?

Кинь тогда скрины ошибок и полный лог.
