### ISSUE TITLE
Unsupported iOS version 

### ISSUE THREAD

**Issue by NicoOrz** [TheOdysseyJB/Odyssey#47]
I have an iPhone on iOS 13.6.1 and jailbroken.For some reason I had to modify the iOS version to 14.2 and reboot system.
Unfortunately when I restarted I can’t use odyssey anymore and it shows unsupported version 
Any way to solve this?

**Comment by demhademha** [comment]
You may be able to modify the supported versions in the app

**Comment by NicoOrz** [comment]
> You may be able to modify the supported versions in the app

yea I am working on it

**Comment by ugcgt** [comment]
[]()

**Comment by ugcgt** [comment]
[]()

**Comment by NicoOrz** [comment]
> If you do find out how to change supported versions, please tell me where's the string located.
> I searched pretty much everywhere, didn't find numerical references.
> (having the same issue! changed 13.7 to 14.4 so the updated would shut and now this.)

Hmm.I cant find it too.At last I use checkra1n to active JB first and change the version back.
